import assert from 'node:assert/strict';
import {after,before,test} from 'node:test';
import {chromium} from 'playwright';
import {launchTestDaemon,resolveChromiumExecutable} from '../support/daemon.mjs';
let runtime,browser;
before(async()=>{runtime=process.env.AXOCOATL_COMPONENT_BASE_URL?{baseUrl:process.env.AXOCOATL_COMPONENT_BASE_URL,stop:async()=>{}}:await launchTestDaemon();const executablePath=await resolveChromiumExecutable();browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});});
after(async()=>{await browser?.close();await runtime?.stop();});
test('Ways retains separate explicit budgets per heterogeneous attempt and rejects missing or expired approval',async()=>{const context=await browser.newContext({viewport:{width:390,height:844},colorScheme:'dark',reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));try{
 await page.route('**/budget-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html data-theme="dark"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/ui/tokens.css"><button>Explore several ways</button><ax-fanout open enabled></ax-fanout><script type="module" src="/ui/fanout.js"></script></html>'}));
 await page.route('**/api/agents',route=>route.fulfill({json:[{id:'coder',role:'autonomous',provider:'ollama',model:'code'},{id:'reviewer',role:'autonomous',provider:'ollama',model:'review'}]}));await page.route('**/api/llm/models?*',route=>route.fulfill({json:['code','review']}));
 await page.goto(`${runtime.baseUrl}/budget-fixture`);await page.waitForFunction(()=>customElements.get('ax-fanout'));await page.locator('ax-fanout').evaluate(element=>element.lanes=[{agent:'coder'},{agent:'reviewer'}]);
 assert.equal(await page.locator('ax-fanout').evaluate(element=>element.validateApprovals()),false);assert.equal(await page.getByLabel('Attempt 1: Activation limit',{exact:true}).inputValue(),'');
 for(const number of [1,2]){await page.locator('ax-fanout').evaluate((element,number)=>{element.shadowRoot.querySelectorAll('details')[number-1].open=true;},number);for(const[label,value]of [['Activation limit','2'],['Invocation limit','10'],['Total token limit','20000'],['Cost limit (USD)','0'],['Maximum output tokens per request','256'],['Budget expires (your local time)','2099-10-10T10:00']])await page.getByLabel(`Attempt ${number}: ${label}`,{exact:true}).fill(value);}
 assert.equal(await page.locator('ax-fanout').evaluate(element=>element.validateApprovals()),true);const lanes=await page.locator('ax-fanout').evaluate(element=>element.lanes);assert.deepEqual(lanes.map(lane=>lane.agent),['coder','reviewer']);assert.equal(lanes[1].approval.max_output_tokens,256);assert.deepEqual(lanes[0].approval.limits,{activations:2,invocations:10,tokens:20000,cost_microunits:0});
 await page.getByRole('button',{name:'+ Add an attempt',exact:true}).click();await page.locator('ax-fanout').evaluate(element=>{element.shadowRoot.querySelectorAll('details')[2].open=true;});await page.getByLabel('Attempt 3: Total token limit',{exact:true}).fill('30000');assert.equal(await page.locator('ax-fanout').evaluate(element=>element.lanes[1].approval.limits.tokens),20000,'Copied attempts do not share a mutable approval');await page.getByLabel('Attempt 3: Budget expires (your local time)',{exact:true}).fill('2000-10-10T10:00');assert.equal(await page.locator('ax-fanout').evaluate(element=>element.validateApprovals()),false);assert.deepEqual(errors,[]);
 }finally{await context.close();}});
