import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {chromium} from 'playwright';
import {launchTestDaemon,resolveChromiumExecutable,newAuthorizedContext} from '../support/daemon.mjs';
let runtime,browser;before(async()=>{runtime=process.env.AXOCOATL_COMPONENT_BASE_URL?{baseUrl:process.env.AXOCOATL_COMPONENT_BASE_URL,stop:async()=>{}}:await launchTestDaemon();browser=await chromium.launch({headless:true,executablePath:await resolveChromiumExecutable()});});after(async()=>{await browser?.close();await runtime?.stop();});
const activation={session_id:'session',turn_id:'turn',execution_epoch_id:'epoch',node_id:'reviewer',activation_id:'activation',generation:1};
async function setup(lose=false,finishNormally=false){const context=await newAuthorizedContext(browser, {viewport:{width:390,height:844},colorScheme:'dark',reducedMotion:'reduce'}),page=await context.newPage(),calls=[],errors=[];page.on('pageerror',error=>errors.push(error.message));let revoked=false;let policy={id:'grant',revision:1,holder:'reviewer',limits:{activations:4,invocations:20,tokens:10000,cost_microunits:0},expires_at_ms:4096902600000,delegation:{operations:[{operation:'stop_activation',targets:{kind:'subtree',root:'reviewer',include_future_descendants:true}}],graph_limits:{max_nodes:8,max_edges:4}}};if(finishNormally)policy.delegation.operations.push({operation:'finish_normally',targets:{kind:'subtree',root:'reviewer',include_future_descendants:true}});await page.route('**/grants-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html data-theme="dark"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/ui/tokens.css"><ax-session-grants></ax-session-grants><script type="module" src="/ui/session-grants.js"></script></html>'}));await page.route('**/api/sessions/session/turns/turn/grants**',route=>{const path=new URL(route.request().url()).pathname.split('/grants')[1],body=route.request().method()==='POST'?route.request().postDataJSON():null;calls.push({path,body});if(path==='/preview')return route.fulfill({json:{request:body,before:policy,after:{...policy,revision:2,limits:body.limits},review_digest:'exact-reviewed'}});if(path==='/revoke')revoked=true;if(path==='/decide'){policy={...policy,revision:2,limits:body.request.limits};if(lose){lose=false;return route.abort('failed');}}return route.fulfill({json:{grants:[{policy,authority_revision:4,revoked_at_revision:revoked?5:null}],proposals:[]}});});await page.goto(`${runtime.baseUrl}/grants-fixture`);const open=()=>page.evaluate(async activation=>{await customElements.whenDefined('ax-session-grants');await document.querySelector('ax-session-grants').open({sessionId:'session',turnId:'turn',controlPlane:{nodes:[{activations:[{reference:{kind:'exact',activation}}]}]}});},activation);await open();return{context,page,calls,errors,open};}
async function edit(page){await page.getByRole('button',{name:'Review limits and permissions',exact:true}).click();await page.getByLabel('Total token limit',{exact:true}).fill('20000');await page.getByLabel('Reason',{exact:true}).fill('Approve remaining review');assert.equal(await page.getByRole('button',{name:'Apply authority change',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Preview authority change',exact:true}).click();await page.getByRole('button',{name:'Apply authority change',exact:true}).click();}
test('current authority review preserves totals and applies exact preview before revocation',async()=>{const{context,page,calls,errors}=await setup();try{await edit(page);await page.getByText('reviewer · grant revision 2',{exact:true}).waitFor();const call=calls.find(item=>item.path==='/decide');assert.equal(call.body.review_digest,'exact-reviewed');assert.deepEqual(call.body.request.activation,activation);assert.equal(call.body.request.limits.tokens,20000);assert.equal(call.body.request.limits.invocations,20);await page.getByRole('button',{name:'Revoke authority',exact:true}).click();await page.getByText('reviewer · grant revision 2 · revoked',{exact:true}).waitFor();assert.deepEqual(calls.find(item=>item.path==='/revoke').body,{grant_id:'grant',expected_grant_revision:2});assert.deepEqual(errors,[]);}finally{await context.close();}});
test('lost authority Apply resolves original request after reload',async()=>{const{context,page,calls,errors,open}=await setup(true);try{await edit(page);await page.getByRole('button',{name:'Resolve pending decision',exact:true}).waitFor();const original=calls.find(item=>item.path==='/decide').body;await page.reload();await open();assert.equal(await page.getByRole('button',{name:'Review limits and permissions',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Resolve pending decision',exact:true}).click();await page.getByText('reviewer · grant revision 2',{exact:true}).waitFor();assert.deepEqual(calls.filter(item=>item.path==='/decide').map(item=>item.body),[original,original]);assert.deepEqual(errors,[]);}finally{await context.close();}});

test('normal Finish permission reflects retained authority and sends the exact delegated wire operation',async()=>{const{context,page,calls,errors}=await setup(false,true);try{await page.getByRole('button',{name:'Review limits and permissions',exact:true}).click();const finish=page.getByLabel('finish normally',{exact:true});assert.equal(await finish.isChecked(),true);await finish.uncheck();await page.getByLabel('Reason',{exact:true}).fill('Review normal Finish permission');await page.getByRole('button',{name:'Preview authority change',exact:true}).click();await page.getByText('Review the exact totals and permissions. Usage already charged remains included.',{exact:true}).waitFor();assert.deepEqual(calls.find(item=>item.path==='/preview').body.operations,['stop_activation']);await finish.check();await page.getByRole('button',{name:'Preview authority change',exact:true}).click();await page.getByRole('button',{name:'Apply authority change',exact:true}).click();await page.getByText('reviewer · grant revision 2',{exact:true}).waitFor();const applied=calls.find(item=>item.path==='/decide').body;assert.deepEqual(applied.request.operations,['stop_activation','finish_normally']);assert.equal(applied.request.operations.includes('finish_turn'),false);assert.deepEqual(errors,[]);}finally{await context.close();}});


test('authority review has an opaque theme surface and Escape stays within the nested dialog',async()=>{
 const{context,page,errors,open}=await setup();
 try{
  await page.evaluate(()=>{window.authorityEscapeLeaks=0;document.addEventListener('keydown',event=>{if(event.key==='Escape')window.authorityEscapeLeaks++;});const underlay=document.createElement('div');underlay.textContent='Graph node behind authority review';underlay.style.cssText='position:fixed;inset:50% 0;color:red;font-size:40px';document.body.prepend(underlay);});
  for(const theme of ['light','dark']){
   await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);
   const colors=await page.getByRole('dialog',{name:'Current work authority',exact:true}).evaluate(dialog=>({background:getComputedStyle(dialog).backgroundColor,expected:getComputedStyle(document.documentElement).getPropertyValue('--panel').trim(),radius:getComputedStyle(dialog).borderRadius}));
   assert.notEqual(colors.background,'rgba(0, 0, 0, 0)');
   assert.equal(colors.background,theme==='light'?'rgb(255, 255, 255)':'rgb(28, 28, 30)');
   assert.equal(colors.radius,'10px');
   if(process.env.AXOCOATL_P1_SCREENSHOT_DIR)await page.screenshot({path:`${process.env.AXOCOATL_P1_SCREENSHOT_DIR}/authority-opaque-${theme}.png`});
  }
  await page.getByRole('button',{name:'Close',exact:true}).press('Escape');
  assert.equal(await page.getByRole('dialog',{name:'Current work authority',exact:true}).isVisible(),false);
  assert.equal(await page.evaluate(()=>window.authorityEscapeLeaks),0);
  await open();await page.getByRole('button',{name:'Close',exact:true}).click();
  assert.deepEqual(errors,[]);
 }finally{await context.close();}
});
