import assert from 'node:assert/strict';
import { after,before,test } from 'node:test';
import { chromium } from 'playwright';
import {launchTestDaemon,resolveChromiumExecutable} from '../support/daemon.mjs';
let runtime,browser;
before(async()=>{runtime=process.env.AXOCOATL_COMPONENT_BASE_URL?{baseUrl:process.env.AXOCOATL_COMPONENT_BASE_URL,stop:async()=>{}}:await launchTestDaemon();const executablePath=await resolveChromiumExecutable();browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{})});});
after(async()=>{await browser?.close();await runtime?.stop();});
async function fixture(action,{loseReply=false,team=null}={}){const context=await browser.newContext({viewport:{width:1000,height:850}}),page=await context.newPage(),calls=[],errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/graph-fixture',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><html data-theme="light"><head><link rel="stylesheet" href="/ui/tokens.css"></head><body><ax-activation-inspector></ax-activation-inspector><script type="module" src="/ui/coordination-turn.js"></script></body></html>'}));
 await page.route('**/api/sessions/session/team',route=>route.fulfill({json:team||{templates:[{slot_id:'reviewer',template_id:'reviewer',source_slot_id:null,name:'Reviewer',provider:'ollama',model:'local-model',instructions:'Verify actual changes.',max_output_tokens:128,required:true,reset_history:true,limits:null,expires_at_ms:null}]}}));
 await page.route('**/api/sessions/session/turns/turn/graph-edits/**',route=>{const body=route.request().postDataJSON();calls.push(body);if(loseReply&&route.request().url().endsWith('/apply')){loseReply=false;return route.abort('failed');}return route.fulfill({json:route.request().url().endsWith('/preview')?{request:body,review_digest:'exact-graph',graph:{revision:2},receipt:null}:{request:body.request,review_digest:body.review_digest,graph:{revision:2},receipt:{state:'settled'}}});});
 await page.goto(`${runtime.baseUrl}/graph-fixture`);await page.waitForFunction(()=>customElements.get('ax-activation-inspector'));
 await page.locator('ax-activation-inspector').evaluate((element,action)=>{const nodes=[{node_id:'parent',label:'Parent',dependencies:[],activations:[]},{node_id:'future',label:'Future reviewer',dependencies:['parent'],activations:[]}];element.model={turnId:'turn',sessionId:'session',historyVersion:'execution_v2',nodes,warnings:[],controlPlane:{schema_version:1,history_version:'execution_v2',state:'running',session_id:'session',turn_id:'turn',turn_revision:{status:'available',value:4},graph_revision:{status:'available',value:1},epochs:{status:'available',value:[{id:'epoch',state:'running'}]},nodes}};element.nodeId=action==='replace'?'future':'parent';},action);
 return{context,page,calls,errors};}
for(const action of ['add','replace'])test(`current-turn inspector ${action} uses exact typed review and explicit limits`,async()=>{const{context,page,calls,errors}=await fixture(action);try{
 await page.getByRole('button',{name:action==='add'?'Add dependent work':'Replace before starting',exact:true}).click();await page.getByText('Enter explicit limits, then Preview',{exact:false}).waitFor();assert.equal(await page.getByLabel('Activation limit',{exact:true}).inputValue(),'');
 for(const[label,input]of [['Task for this Agent','Check the exact output'],['Activation limit','2'],['Provider and tool invocation limit','5'],['Total token limit','16000'],['Cost limit (USD)','0'],['Budget expires (your local time)','2099-10-10T10:00']])await page.getByLabel(label,{exact:true}).fill(input);
 await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByText('The new work is required;', {exact:false}).waitFor();assert.equal(calls[0].action,action);assert.equal(calls[0].expected_turn_revision,4);assert.equal(calls[0].expected_graph_revision,1);assert.equal(calls[0].execution_epoch_id,'epoch');assert.deepEqual(calls[0].dependencies,action==='add'?['parent']:[]);assert.equal(calls[0].replacement,action==='replace'?'future':null);assert.equal(calls[0].agent.limits.cost_microunits,0);
 await page.getByRole('button',{name:'Apply to this turn',exact:true}).click();await page.getByText('Graph change settled.',{exact:false}).waitFor();assert.deepEqual(calls[1],{request:calls[0],review_digest:'exact-graph'});assert.deepEqual(errors,[]);
 }finally{await context.close();}});

test('graph Apply lost reply remains reachable after reload into NeedsAttention',async()=>{const{context,page,calls,errors}=await fixture('add',{loseReply:true});try{
 await page.getByRole('button',{name:'Add dependent work',exact:true}).click();await page.getByText('Enter explicit limits, then Preview',{exact:false}).waitFor();
 for(const[label,input]of [['Task for this Agent','Check the exact output'],['Activation limit','2'],['Provider and tool invocation limit','5'],['Total token limit','16000'],['Cost limit (USD)','0'],['Budget expires (your local time)','2099-10-10T10:00']])await page.getByLabel(label,{exact:true}).fill(input);
 await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByText('The new work is required;', {exact:false}).waitFor();await page.getByRole('button',{name:'Apply to this turn',exact:true}).click();await page.getByText('Retry the exact saved Apply',{exact:false}).waitFor();
 const model=await page.locator('ax-activation-inspector').evaluate(element=>element.model);model.controlPlane.state='needs_attention';await page.reload();await page.waitForFunction(()=>customElements.get('ax-activation-inspector'));await page.locator('ax-activation-inspector').evaluate((element,model)=>{element.model=model;element.nodeId='parent';},model);
 assert.equal(await page.getByRole('button',{name:'Add dependent work',exact:true}).count(),0);await page.getByRole('button',{name:'Resolve pending graph change',exact:true}).click();await page.getByRole('button',{name:'Apply to this turn',exact:true}).click();await page.getByText('Graph change settled.',{exact:false}).waitFor();assert.deepEqual(calls[1],calls[2]);assert.deepEqual(errors,[]);
 }finally{await context.close();}});

test('added work starts from the Session team\'s Agent and keeps what it may change',async()=>{
 const helper={slot_id:'slot-helper',template_id:null,source_slot_id:null,name:'Helper',provider:'ollama',model:'team-model',instructions:'Only read.',max_output_tokens:64,writes:[],required:true,reset_history:false,limits:{activations:1,invocations:2,tokens:100,cost_microunits:0},expires_at_ms:1};
 const{context,page,calls,errors}=await fixture('add',{team:{slots:[helper],templates:[{slot_id:'slot-reviewer',template_id:'reviewer',source_slot_id:null,name:'Reviewer',provider:'ollama',model:'local-model',instructions:null,max_output_tokens:128,writes:null,required:true,reset_history:true,limits:null,expires_at_ms:null}]}});try{
 await page.getByRole('button',{name:'Add dependent work',exact:true}).click();await page.getByText('Enter explicit limits, then Preview',{exact:false}).waitFor();
 await page.getByText('May change: nothing (read-only helper).',{exact:false}).waitFor();assert.equal(await page.getByLabel('Model',{exact:true}).inputValue(),'team-model');
 for(const[label,input]of [['Task for this Agent','Check the exact output'],['Activation limit','2'],['Provider and tool invocation limit','5'],['Total token limit','16000'],['Cost limit (USD)','0'],['Budget expires (your local time)','2099-10-10T10:00']])await page.getByLabel(label,{exact:true}).fill(input);
 await page.getByRole('button',{name:'Preview change',exact:true}).click();await page.getByText('The new work is required;', {exact:false}).waitFor();
 assert.equal(calls[0].agent.source_slot_id,'slot-helper');assert.equal(calls[0].agent.template_id,null);assert.deepEqual(calls[0].agent.writes,[]);assert.notEqual(calls[0].agent.slot_id,'slot-helper');assert.deepEqual(errors,[]);
 }finally{await context.close();}});
