#!/bin/sh
# A fake `claude` for the tests of `axocoatl connect claude-code`. It acts
# like `claude setup-token`: prompts, waits for a keypress (Enter), then
# prints the token in the file `token` beside it, the way the file `mode`
# names:
#   colored  ANSI colors around the token and a color change inside it
#   split    the token in three write() calls, two inside its prefix, with
#            pauses longer than the relay's idle flush
#   wrapped  lines exactly as wide as the terminal when it is narrower than
#            200 columns (how a narrow terminal wraps it), else one line
#   twice    the same token twice
#   two      two different tokens
#   none     no token; exits 1
#   linger   like colored, then exits leaving a process that holds the
#            terminal open for 3 seconds
#   replay   what Claude Code's renderer writes, generated by the tests for
#            each terminal size ROWSxCOLS: writes `before-COLSxROWS`, then
#            waits for Enter in raw mode (as Node's setRawMode sets it),
#            printing `[SIGWINCH]` on that signal and `[size ROWS COLS]` when
#            its terminal's size changes, then writes `after-COLSxROWS` for
#            the size it has then, cut into writes with pauses at the byte
#            offsets in `cuts` when that file exists
# It never reads its environment for the token, and writes nowhere else.
set -u
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
if [ "${1:-}" != "setup-token" ] || [ "$#" -ne 1 ]; then
  printf 'fake claude: unexpected arguments: %s\n' "$*" >&2
  exit 64
fi
mode=$(cat "$here/mode")
token=$(cat "$here/token")
if [ "$mode" = replay ]; then
  # Raw before anything is drawn, as Claude Code is.
  saved=$(stty -g)
  stty -icanon -echo -icrnl -isig -iexten min 0 time 1
  trap 'printf "[SIGWINCH]"' WINCH
  size=$(stty size)
  cat "$here/before-${size#* }x${size% *}"
  while :; do
    key=$(dd bs=1 count=1 2>/dev/null | od -An -tu1 | tr -d ' \n')
    now=$(stty size)
    if [ "$now" != "$size" ]; then
      size=$now
      printf '[size %s]' "$size"
    fi
    [ "$key" = 13 ] && break
  done
  after="$here/after-${size#* }x${size% *}"
  if [ -f "$here/cuts" ]; then
    start=0
    for cut in $(cat "$here/cuts"); do
      tail -c +$((start + 1)) "$after" | head -c $((cut - start))
      sleep 0.4
      start=$cut
    done
    tail -c +$((start + 1)) "$after"
  else
    cat "$after"
  fi
  stty "$saved"
  exit 0
fi
printf '\033[2J\033[H\033[1mWelcome to Claude Code\033[0m\n'
printf 'Browser did not open? Use the url below to sign in:\n\n'
printf '  https://claude.ai/oauth/authorize?code=true&client_id=fake-client\n\n'
printf 'Press Enter to continue\n'
IFS= read -r _ || exit 70
cols=$(stty size 2>/dev/null | cut -d' ' -f2)
if [ "$mode" = none ]; then
  printf 'Error: the sign-in was cancelled\n'
  exit 1
fi
printf '\033[32m\342\234\223\033[0m Long-lived authentication token created successfully!\n\n'
printf 'Your OAuth token (valid for 1 year):\n\n'
case "$mode" in
  colored|linger)
    head=$(printf '%s' "$token" | cut -c1-40)
    tail=$(printf '%s' "$token" | cut -c41-)
    printf '\033[1m\033[38;5;214m%s\033[0m\033[38;2;10;200;30m%s\033[0m\n' "$head" "$tail"
    ;;
  split)
    first=$(printf '%s' "$token" | cut -c1-4)
    second=$(printf '%s' "$token" | cut -c5-30)
    third=$(printf '%s' "$token" | cut -c31-)
    printf '\033[33m%s' "$first"
    sleep 0.4
    printf '%s' "$second"
    sleep 0.3
    printf '\033[1m%s\033[0m\n' "$third"
    ;;
  wrapped)
    if [ "${cols:-0}" -gt 0 ] && [ "${cols:-0}" -lt 200 ]; then
      printf '\033[36m'
      printf '%s\n' "$token" | fold -w "$cols"
      printf '\033[0m'
    else
      printf '\033[36m%s\033[0m\n' "$token"
    fi
    ;;
  twice)
    printf '%s\n\nexport CLAUDE_CODE_OAUTH_TOKEN=%s\n' "$token" "$token"
    ;;
  two)
    other="sk-ant-oat01-$(printf '%s' "$token" | cut -c14- | tr 'a-f' 'g-l')"
    printf '%s\n%s\n' "$token" "$other"
    ;;
esac
printf '\nStore this token securely. You will not be able to see it again.\n'
if [ "$mode" = linger ]; then
  (trap '' HUP; exec sleep 3) &
fi
exit 0
